/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package poker.practica2.hja.GUI;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import poker.practica2.hja.ap1.Ap1;
import poker.practica2.hja.ap1.Ap2;

/**
 *
 * @author jjcar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RangeGrid = new poker.practica2.hja.GUI.RangeGrid();
        RangeTextPanel = new javax.swing.JPanel();
        RangeText = new javax.swing.JTextField();
        ButtonPanel = new javax.swing.JPanel();
        rep_range_button = new javax.swing.JButton();
        Get_Range_button = new javax.swing.JButton();
        clear_button = new javax.swing.JButton();
        SliderPanel = new javax.swing.JPanel();
        SliderNumber = new javax.swing.JLabel();
        RangeSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica 2");
        setResizable(false);

        RangeTextPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Range Text", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N

        RangeText.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N

        javax.swing.GroupLayout RangeTextPanelLayout = new javax.swing.GroupLayout(RangeTextPanel);
        RangeTextPanel.setLayout(RangeTextPanelLayout);
        RangeTextPanelLayout.setHorizontalGroup(
            RangeTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RangeTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RangeText)
                .addContainerGap())
        );
        RangeTextPanelLayout.setVerticalGroup(
            RangeTextPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RangeTextPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RangeText, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rep_range_button.setIcon(new javax.swing.ImageIcon("H:\\UCM\\3\\HJA\\Practica2_HJA\\Practica2-HJA\\icons\\Icon input 3.png")); // NOI18N
        rep_range_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rep_range_buttonActionPerformed(evt);
            }
        });

        Get_Range_button.setIcon(new javax.swing.ImageIcon("H:\\UCM\\3\\HJA\\Practica2_HJA\\Practica2-HJA\\icons\\Icon output 3.png")); // NOI18N
        Get_Range_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Get_Range_buttonActionPerformed(evt);
            }
        });

        clear_button.setIcon(new javax.swing.ImageIcon("H:\\UCM\\3\\HJA\\Practica2_HJA\\Practica2-HJA\\icons\\clear_icon.png")); // NOI18N
        clear_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rep_range_button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Get_Range_button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addComponent(clear_button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Get_Range_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rep_range_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        SliderNumber.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        SliderNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SliderNumber.setText("0 %");

        RangeSlider.setMajorTickSpacing(10);
        RangeSlider.setMinorTickSpacing(1);
        RangeSlider.setPaintLabels(true);
        RangeSlider.setPaintTicks(true);
        RangeSlider.setSnapToTicks(true);
        RangeSlider.setValue(0);
        RangeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                RangeSliderStateChanged(evt);
            }
        });

        javax.swing.GroupLayout SliderPanelLayout = new javax.swing.GroupLayout(SliderPanel);
        SliderPanel.setLayout(SliderPanelLayout);
        SliderPanelLayout.setHorizontalGroup(
            SliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SliderPanelLayout.createSequentialGroup()
                .addComponent(RangeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
        );
        SliderPanelLayout.setVerticalGroup(
            SliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SliderPanelLayout.createSequentialGroup()
                .addGroup(SliderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(SliderPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SliderNumber)
                        .addGap(12, 12, 12))
                    .addGroup(SliderPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(RangeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SliderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RangeGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RangeTextPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RangeTextPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RangeGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SliderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rep_range_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rep_range_buttonActionPerformed
        // TODO add your handling code here:
        Text2Range();
    }//GEN-LAST:event_rep_range_buttonActionPerformed

    private void Get_Range_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Get_Range_buttonActionPerformed
        // TODO add your handling code here:
        Range2Text();
    }//GEN-LAST:event_Get_Range_buttonActionPerformed

    private void clear_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_buttonActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_clear_buttonActionPerformed

    private void RangeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_RangeSliderStateChanged
        // TODO add your handling code here:
        moveSlider();
    }//GEN-LAST:event_RangeSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JButton Get_Range_button;
    private poker.practica2.hja.GUI.RangeGrid RangeGrid;
    private javax.swing.JSlider RangeSlider;
    private javax.swing.JTextField RangeText;
    private javax.swing.JPanel RangeTextPanel;
    private javax.swing.JLabel SliderNumber;
    private javax.swing.JPanel SliderPanel;
    private javax.swing.JButton clear_button;
    private javax.swing.JButton rep_range_button;
    // End of variables declaration//GEN-END:variables

    /*Metodo que se llama cuando presionas el boton para marcar en la tabla
    el rango especificado en el campo de texto.*/
    private void Text2Range(){
        
        RangeGrid.clear();
        
        Ap1 logic = new Ap1(RangeText.getText());
        
        for(String text : logic.rangos){
            RangeGrid.searchButton(text,true);
        }
    }
    
    private void Range2Text(){
        
        RangeGrid.checkSelected();
        
        //DEBUG--------------------------------------
        ArrayList<String> test = new ArrayList<>();
        test = RangeGrid.getSelButtonList();
        
        for( String s : test){
            System.out.println(s);
        }
        //--------------------------------------
        
        Ap1 logic = new Ap1(RangeGrid.getSelButtonList());
        
        logic.fillRange2Text(RangeGrid.getSelButtonList());
       
        RangeText.setText(logic.texfield);
    }
    
    private void clear(){
        RangeGrid.clear();
        RangeText.setText("");
    }
    
    private void moveSlider(){
        int slider_value = RangeSlider.getValue();
        ArrayList<String> percent_range = new ArrayList<>();
        String file="rangos"+".txt";
        
        SliderNumber.setText(Integer.toString(slider_value) + " %");
        
        RangeGrid.clear();
        readFile(file,percent_range);

        Ap2 logic = new Ap2(percent_range, slider_value);
        
        RangeGrid.selectSliderRange(logic.result);
        
        
    }
    
    private void readFile(String file,ArrayList<String> aux){
        
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
           while ((line = br.readLine()) != null) {
              aux.add(line);
              
           }   
        }
        
        catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    }

