/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package poker.practica2.hja.GUI;

import java.awt.Color;

/**
 *
 * @author jjcar
 */
public class RangeGrid extends javax.swing.JPanel {
    
    private final static int _size = 14;

    /**
     * Creates new form RangeGrid
     */
    public RangeGrid() {
        initComponents();
        createButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(13, 13));
    }// </editor-fold>//GEN-END:initComponents

    //Crea la matriz de botones que van a representar el rango.
    private void createButtons(){
        
        //Recorre la tabla
        for (int i = _size; i >= 2; i-- ){
            for(int j = _size; j >= 2; j--){
                
                //Creacion del boton y atributos
                javax.swing.JButton pair = new javax.swing.JButton();
                pair.setSize(100, 100);
                
                //Botones de las Parejas
                if( i == j ){
                    pair.setText(rangeButtonText(i) + 
                            rangeButtonText(j));
                    pair.setBackground(Color.magenta);
                    
                }
                // Botones de las cartas Suited
                else if ( i > j){
                    pair.setText(rangeButtonText(i) + 
                            rangeButtonText(j) +
                            "s");
                    pair.setBackground(Color.CYAN);
                }
                // Botones de las cartas Offsuit
                else if( i < j ){
                    pair.setText(rangeButtonText(j) + 
                            rangeButtonText(i) +
                            "o");
                    pair.setBackground(Color.BLUE);
                    pair.setForeground(Color.WHITE);
                }
                
                
                add(pair);
            }
        }
    }
    
    // Metodo para escribir el texto de las cartas en el boton
    private String rangeButtonText(int i){
        
        String text = "";
        
        switch(i){
            case 14:
                text += "A";
                break;
            case 13:
                text += "K";
                break;
            case 12:
                text += "Q";
                break;
            case 11:
                text += "J";
                break;
            case 10:
                text += "T";
                break;
            default:
                text += Integer.toString(i);
                break;
                
        }
        
        return text;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
